app:
  name: "garesearch"
  frontend-host: ${APP_FRONTEND-HOST}
  static-host: "https://static.gatorapps.org"
  prod-status: ${APP_PROD-STATUS}
  database:
    global: "global"
    account: "account"
    garesearch: "garesearch"
  session:
    cookie:
      secret: ${APP_SESSION_COOKIE_SECRET}
  user:
    auth:
      token:
        public-key: ${APP_USER_AUTH_TOKEN_PUBLIC-KEY}

spring:
  application:
    name: "garesearch"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  session:
    store-type: "mongodb"

server:
  port: ${PORT:8500}
  servlet:
    session:
      cookie:
        name: "GATORAPPS_GLOBAL_SID"
        domain: "gatorapps.org"

session:
  global-cookie-name: "GATORAPPS_GLOBAL_SID"
  lifespan: 43200000
  auth-token-lifespan: "12h"
  max-web-sessions: 2

aws:
  accessKeyId: ${AWS_ACCESSKEYID}
  secretKey: ${AWS_SECRETKEY}
  s3:
    region: "us-east-1"
    bucket-name: "research-dev-gatorapps-org"
  ses:
    region: "us-east-1"
    default-sender-name: "RESEARCH.UF"
    default-sender-address: "research-no-reply@gatorapps.org"
