app:
  name: "garesearch"
  frontend-host: "https://templateapp.dev-local.gatorapps.org:3500"
  prod-status: "dev"

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

session:
  global-cookie-name: "GATORAPPS_GLOBAL_SID"
  lifespan: 43200000
  auth-token-lifespan: "12h"
  max-web-sessions: 2

aws:
  s3:
    region: "us-east-1"
    bucket-name: "research-dev-gatorapps-org"
  ses:
    region: "us-east-1"
    default-outbound-address: ""
