app:
  name: "garesearch"
  frontend-host: "https://templateapp.dev-local.gatorapps.org:3500"
  prod-status: "dev"

session:
  global-cookie-name: "GATORAPPS_GLOBAL_SID"
  lifespan: 43200000
  auth-token-lifespan: "12h"
  max-web-sessions: 2

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
