= GatorApps REST Documentation
:doctype: book
:icons: font
:source-highlighter: highlight.js
:toc: left
:toclevels: 2
:sectlinks:
:stylesheet: ./asciidoctor-default-stylesheet.css


== Applicant Routes

[[index-get-applicant-resume-metadata]]
=== GET ResumeMetadata
A `GET` request to retrieve an Applicant's Resume metadata.

operation::applicant-resume-metadata-get[snippets='http-request,http-response']


[[index-get-applicant-transcript-metadata]]
=== GET TranscriptMetadata
A `GET` request to retrieve an Applicant's Transcript metadata.

operation::applicant-transcript-metadata-get[snippets='http-request,http-response']


[[index-post-applicant-resume]]
=== POST Resume
A `POST` request to upload an Applicant's Resume.

operation::applicant-resume-post[snippets='http-request,http-response']

[[index-post-applicant-transcript]]
=== POST Transcript
A `POST` request to upload an Applicant's Transcript.

operation::applicant-transcript-post[snippets='http-request,http-response']


== Application Routes

[[index-get-application-by-id]]
=== GET StudentApplication
A `GET` request to retrieve a single Application.

operation::application-get-by-id[snippets='http-request,http-response']


[[index-get-application-student-list]]
=== GET StudentList
A `GET` request to retrieve a list of Applications associated with a particular User.

operation::application-get-studentList[snippets='http-request,http-response']

[[index-get-application-already-applied]]
=== GET AlreadyApplied
A `GET` request to retrieve information on whether a student has already applied to a certain Posting.

operation::application-alreadyApplied[snippets='http-request,http-response']

[[index-post-application]]
=== POST SubmitApplication
A `POST` request to Submit a single Application for a specific Position.

operation::application-post-submit[snippets='http-request,http-response']

== Application Faculty Only Routes

[[index-get-faculty]]
=== GET Application
A `GET` request to retrieve a single Application

operation::application-get-faculty[snippets='http-request,http-response']

[[index-get-application-management-list]]
=== GET ApplicationManagementList
A `GET` request to retrieve a list of Applications for a particular Position.

operation::application-get-mgmt-list[snippets='http-request,http-response']

[[index-update-application-status]]
=== PUT Application Status
A `PUT` request to update the status of an Application within the Application Management page.

operation::application-update-status[snippets='http-request,http-response']


== Lab Routes

[[index-get-lab-by-id]]
=== GET Lab by ID
A `GET` request used to retrieve a Lab's details including associated open Positions by its unique `labId`.

operation::lab-get-by-id[snippets='http-request,http-response']

== Lab Faculty Only Routes

[[index-get-lab-list]]
=== GET LabList
A `GET` request to retrieve a list of Labs a user is in.

operation::lab-get-list[snippets='http-request,http-response']

[[index-get-lab]]
=== GET Lab
A `GET` request to retrieve a Lab for editing purposes.

operation::lab-faculty-get-by-id[snippets='http-request,http-response']

[[index-post-lab]]
=== POST Create New Lab
A `POST` request to create a new Lab.

operation::lab-create-new[snippets='http-request,http-response']

[[index-update-lab]]
=== PUT Update Existing Lab
A `PUT` request to update an existing Lab.

operation::lab-update-existing[snippets='http-request,http-response']



== Messages Routes

[[index-get-message-by-id]]
=== GET Message by ID
A `GET` request used to retrieve a Message by its unique `messageId`.

operation::msg-get-single[snippets='http-request,http-response']


[[index-get-message-list]]
=== GET Message List
A `GET` request used to retrieve a list of Messages sent to and from the User.

operation::msg-get-list[snippets='http-request,http-response']


[[index-put-message-list]]
=== PUT IsRead
A `PUT` request used to update the read status of a message.

operation::msg-put-read-status[snippets='http-request,http-response']


[[index-get-message-page]]
=== GET MessagePage
A `GET` request used to retrieve the page number of a Message.

operation::msg-get-page[snippets='http-request,http-response']


== Position Routes

[[index-get-position-by-id]]
=== GET Position by ID
A `GET` request used to retrieve a Position by its unique `positionId`.

operation::position-get-posting-by-id[snippets='http-request,http-response']


[[index-get-position-searchresults]]
=== GET Position Search Results
A `GET` request to search for Positions based on a search query.

operation::position-get-searchresults[snippets='http-request,http-response']


[[index-get-position-searchresults-indexer]]
=== GET Position Search Results (Indexer)
A `GET` request to search for Positions based on a search query. This request returns a condensed list of information.

operation::position-get-searchresults_indexer[snippets='http-request,http-response']


[[index-get-supplemental-questions]]
=== GET SupplementalQuestions
A `GET` request to retrieve the Supplemental Questions for a particular Position.

operation::position-get-supplemental-questions[snippets='http-request,http-response']


== Posting Faculty Only Routes

[[index-get-position-list]]
=== GET PositionList
A `GET` request to retrieve a list of Positions posted by the Labs a User is in.

operation::position-get-list[snippets='http-request,http-response']

[[index-get-position-management-list]]
=== GET PositionManagementList
A `GET` request to retrieve a list of positions posted by the labs a user is in.

operation::position-get-management-list[snippets='http-request,http-response']

[[index-get-position]]
=== GET Position
A `GET` request to retrieve a Position for editing purposes.

operation::position-get-posting-editor[snippets='http-request,http-response']

[[index-post-position]]
=== POST Create New Position
A `POST` request to create a new Position.

operation::position-create-new[snippets='http-request,http-response']

[[index-update-position]]
=== PUT Update Existing Position
A `PUT` request to update an existing Position.

operation::position-update-existing[snippets='http-request,http-response']


[[index-update-position-status]]
=== PUT Position Status
A `PUT` request to update the status of a Position within the Position Management page.

operation::position-update-status[snippets='http-request,http-response']
